name: Publish release to NPM
on:
  release:
    types: [created]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      # TODO: Fix this not having +x permission
      - run: bash -eux ./build.sh
      # This --access=public flag is needed for @<scope>/<package> packages since they
      # default to --access=private which you likely don't want
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
